Update logic to identify clinics that require template unit creation
crassula-ovata/data_and_analytics_dbt_bha_ladders pull request #140
Opened 2024-09-09 15:38 UTC by binrai

[Add additional condition on template case creation, to prevent "gap" effects](https://dimagi.atlassian.net/jira/software/projects/UDA/boards/227?assignee=60a1962f2614ec006899bca4&selectedIssue=UDA-2036)

New condition for template unit creation:

1. A clinic does not have any (open or closed) child unit cases
2. If a clinic does have only closed unit cases, the most recently closed unit cases is more than 2 hours ago.

2024-09-09 16:43 UTC, Joe-Mooney commented
I noticed that a bunch of staging workflows were added to this branch.  Unfortunately github doesn't list workflows that haven't been merged to the main branch in actions.  If the goal of adding these workflows is to use them for testing this branch, I recommend breaking this into 2 PRs - one with the workflows that I can review and merge first, and then another with the functional code changes that I can review and merge afterwards so I can run it through all the staging workflows to test it.

2024-09-09 17:18 UTC, Joe-Mooney requested changes
I have some changes requested for the functional part of the code.  I can review the workflows and yml updates separately now!

2024-09-09 17:18 UTC, Joe-Mooney commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and timestampdiff(hour,current_timestamp_mtn, closed_timestamp_mtn) > 2
This won't work exactly as coded.  There are two issues that need to be addressed:

1. timestampdiff returns an integer difference, not a float, so if it has been 2 hours and 59 minutes, it will just return 2.  So if you check if it is greater than 2, then you will only detect it for things with a 3 hour time difference or greater.  I would recommend doing >= 2 rather than > 2, and changing the wording to state "clinic cases with unit case that was most recently closed 2 hours ago or longer".  First though I would confirm with whoever requested this ticket that it is ok to create the template if the last unit case was closed exactly 2 hours ago - I assume they will probably say it is fine, but if it must be strictly for things more than 2 hours ago, we can revisit this issue and try coding another way.
2. The order of timestamps in timestampdiff changes whether you get a positive or negative result.  You want to flip the order of the dates in your current statement in order to get a positive result to compare against.

2024-09-09 17:18 UTC, Joe-Mooney commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and (case_id not in (select parent_case_id from dm_table_data_unit where closed=false))
Perhaps I am misunderstanding the logic, so if I am incorrect just let me know, but if the goal is to get the union between clinics with no unit cases open or closed, and those with the most recent closure over 2 hours ago, should this first part of the union instead have this logic: `(case_id not in (select parent_case_id from dm_table_data_unit))`?  Because if there is one that is closed we don't want to include it in the first part of the union?

2024-09-09 20:01 UTC, binrai commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and (case_id not in (select parent_case_id from dm_table_data_unit where closed=false))
@Joe-Mooney  I'll confess, I've gone in circle on this. I went with the above because my thought process is following -- If there is clinicA, and unitA (parent_id: clinicA, closed=True).  The first section of the union should not capture this, but the second section should. If we remove the `closed=false` in the first section then the first section would also capture this.

2024-09-09 20:03 UTC, binrai commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and timestampdiff(hour,current_timestamp_mtn, closed_timestamp_mtn) > 2
1. Agree - updated to  >= 2.  The exactness of 2 hours is okay .
2. Swapped the timestamp order

2024-09-09 20:03 UTC, binrai commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +    select parent_case_id,
Updated

2024-09-09 20:48 UTC, shuclu commented
@Joe-Mooney the staging workflows are already in MAIN branch, so you can ignore them here

2024-09-09 21:38 UTC, Joe-Mooney commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and (case_id not in (select parent_case_id from dm_table_data_unit where closed=false))
I think you will need to remove the `closed=false` since in the first query you are matching against everything not in that select query, so you will want to include both clinics that are opened and closed in it so you can exclude both.  However, we could test it with some fake data if that would help - just move the relevant queries out to a worksheet and fake the needed data from ctes or tables.  Then you can test if the logic is working how you intend without having to interact with real data.  You can fake data like this:
```
WITH fake_data AS (
    SELECT
        $1 as col_1,
        $2 as col_2,
        $3 as col_3
    FROM (
        VALUES
            (1, 'A', TO_DATE('2024-01-01')),
            (2, 'B', TO_DATE('2024-01-02'))
    )
)
...
;
```
Just replace the values with the relevant fields, the col_x's with the appropriate column names, and name it the proper name to replace the table or cte from your original query - for example, in this case you would probably need fake data for `dm_table_data_unit` and `dm_table_data_clinic`.

2024-09-09 22:07 UTC, Joe-Mooney commented
> @Joe-Mooney the staging workflows are already in MAIN branch, so you can ignore them here

How did they reach the main branch without reaching ladders-dev out of curiosity?

2024-09-09 22:50 UTC, shuclu commented
@Joe-Mooney 
> How did they reach the main branch without reaching ladders-dev out of curiosity?
it did. i merged them from my branch to ladders-dev, qa and then main, then all other testing env.
what you saw here is binita getting the changes from ladders-dev into her own testing branch

2024-09-09 22:53 UTC, binrai commented on models/DM/VW_UNIT_TEMPLATE_CREATE.sql
> +        and (case_id not in (select parent_case_id from dm_table_data_unit where closed=false))
@Joe-Mooney  you are correct. I have removed the `closed=false` condition. Thanks for the explanation and the patience ❤️

2024-09-10 15:39 UTC, Joe-Mooney approved these changes
This looks good to me now!

2024-09-10 15:40 UTC, Joe-Mooney commented
@binrai - Let me know when you are ready for me to begin the deployment process.  And to confirm, you tested this all in test first in DBT, correct?

2024-09-10 15:54 UTC, binrai commented
@Joe-Mooney  yes, tests have been ran. So, this is ready for deployment to the dev.

2024-09-10 18:54 UTC, merged

2024-09-10 20:18 UTC, binrai commented
@Joe-Mooney  So, this is the first time, but this code will not be deployed to other environments. The delivery team realized the ask wasn't exactly what they wanted/needed, and have updated the ticket requirements drastically. Because of that I am pushing the work to next sprint entirely. 

I am going to defer to you, and/or Shu, in terms of rolling back this changes from the dev.